server:
  port: 9000

spring:
  datasource:
      url: jdbc:mysql://localhost:3306/spring_jwt
      username: root
      password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true

